### ISSUE TITLE
"Download separate album artwork" for Singles downloads a 1KB blank Cover.jpg

### ISSUE THREAD

**Issue by Rings4** [defvs/monsterutilities#21]
Very glad you revived this! Thanks a bunch! Couple small bugs I'm noticing on my end:

The cover.jpeg is blank despite the cover art successfully being embedded in the FLAC.

![image](https://user-images.githubusercontent.com/32050292/141041171-58d7917d-8dea-4ddd-9b20-78056a0c8663.png)

As well, the "size" cannot be adjusted. Usually 0 is supposed to be the "source" size, as in no resizing is being done. However I cannot change it from 0.

![image](https://user-images.githubusercontent.com/32050292/141041072-630a2f01-5eed-4e82-98f8-2b990ccbb953.png)

EDIT: The artwork is actually a single pixel. That's funny. Behold:
![Cover](https://user-images.githubusercontent.com/32050292/141041974-9fe18cae-e989-466e-a49b-b5d2102f0644.jpeg)

**Comment by defvs** [comment]
The problem lies in the cover art size not being editable! haha. Let me fix that.

**Comment by defvs** [comment]
EDIT: it seems that once you go down to 0, you cannot increment the Cover art size again.

**Comment by defvs** [comment]
Fixed in 9b0fe947

**Comment by defvs** [comment]
Closed in latest release.
