### ISSUE TITLE
Subfolders not applying to downloaded releases

### ISSUE THREAD

**Issue by Ampig** [defvs/monsterutilities#24]
The downloader is not sorting downloaded releases into the subfolders that are configured.

![Capture](https://user-images.githubusercontent.com/38151225/142749415-62848810-b0e3-4667-b280-61e6455bae4f.PNG)
![image](https://user-images.githubusercontent.com/38151225/142749353-806ab212-28d0-4d55-ad3b-0a9f756055df.png)
![Capture](https://user-images.githubusercontent.com/38151225/142749371-06ee829f-e47b-4d2c-be4e-e8980581a3ac.PNG)

**Comment by TobiasFaller** [comment]
The field attribute specifies the corresponding response field with the name `ArtistTitle`.
However, according to the documentation at [https://github.com/defvs/connect-v2-docs/wiki/](https://github.com/defvs/connect-v2-docs/wiki/Global-JSON-Objects#release-object) this field is named `ArtistsTitle`.
I assume this is the issue why the directories are not created.
https://github.com/defvs/monsterutilities/blob/735211a4a6a48904f97c6e00090a29af4556d120/src/main/xerus/monstercat/api/response/Release.kt#L15

**Comment by defvs** [comment]
Will be released in the next update.
