### ISSUE TITLE
Unselectable files are selected and downloaded

### ISSUE THREAD

**Issue by Hallikas** [defvs/monsterutilities#6]
Version: dev329-e0e8bec (latest as 27-Sep-2019)

On Downloader tab, when selecting all from top of tree, like 'Album', also 'masked' (unselectable/red) is also selected at same time. Downloader also downloads those.

All unselectable should be unselected after selecting multiple items from top selector.

- Semi

**Comment by defvs** [comment]
Thanks for the report. If I understand well, ticking the box of a top-level tree item (ex. Album or Single) will tick everything under it, including the disabled ones.

**Comment by Hallikas** [comment]
> ticking the box of a top-level tree item (ex. Album or Single) will tick everything under it, including the disabled ones.

Yes that's correct. It does also downloads those, "restricted" items.

**Comment by defvs** [comment]
I will fix it tonight, thanks.

**Comment by defvs** [comment]
Fixed in f499e9e2e9720aa7b790b42b71a450b31ada6348

**Comment by defvs** [comment]
A new release will soon come including this fix

**Comment by defvs** [comment]
Released in https://github.com/defvs/monsterutilities/releases/tag/dev326-ef0745b
