### ISSUE TITLE
Length Header at catalog page is too narrow, and unresizable

### ISSUE THREAD

**Issue by Hallikas** [defvs/monsterutilities#7]
Version: dev329-e0e8bec
(Compared to official dev139-3fae210, latest release)

Like title says, length header at catalog tab is too narrow. It seems that HH: has been added into it, but width is limited to 5 chars (now it is 8 HH:MM:SS, instead of MM:SS).
User can't resize it, because that width is hardcoded. It seems that any of header widths are not changeable.

![image](https://user-images.githubusercontent.com/681531/65768445-a63e5880-e139-11e9-88ae-709b68fc6905.png)

**Comment by defvs** [comment]
Not my ressort, please see Xerus2000#65

**Comment by Hallikas** [comment]
But as you can see from included screenshot. Official version does not have hours part in time, but your version have. So I’m quite sure that modify makes this ticket valid to your version. I mentioned resize only because it could be possible fix/workaround.

**Comment by defvs** [comment]
You are probably running the latest Github release of the official version. I never modified the catalog tab in my custom build, so it probably comes from a newer commit of the official version that is yet to be released (Xerus2000 doesn't release every single modification unlike I do)

**Comment by defvs** [comment]
Yup it's this one https://github.com/Xerus2000/monsterutilities/commit/cb053de63410ca92f50a2f63faca8d719345a187
It was made in late July, latest release was 3 July

**Comment by defvs** [comment]
This bug still exists and I'll fix it in this branch if I find what's causing it.

**Comment by defvs** [comment]
Partially fixed with 4a487fabdcab51cfcb69f4a74dbc2a893c4998cf

**Comment by defvs** [comment]
Last commit did the job, although the size is not automatic anymore, this is much more useable. Closing for now.
