### ISSUE TITLE
ie. Uncaged album should be disabled in streamer mode

### ISSUE THREAD

**Issue by Hallikas** [defvs/monsterutilities#8]
Version: dev329-e0e8bec

Recarding to 'non-licensable-tracks', ungaged album is not allowed in streamer mode.

I have streamer mode on, but uncaged albums is shown as available:
![image](https://user-images.githubusercontent.com/681531/65769381-1b129200-e13c-11e9-8b19-e79d39b136b9.png)

**Comment by defvs** [comment]
Available in the Downloader tab ? Or when playing it ?

**Comment by defvs** [comment]
Because when in streamer mode, you still CAN see unlicensable tracks in the Catalog tab, but trying to play them will result in an warning message and them not playing.

**Comment by Hallikas** [comment]
It was on catalog mode. I wish I could see only tracks that are available for play, so I can select tracks to play. I wish that MonsterCat would do better tools by them self, but even player on their site is not usable.

**Comment by defvs** [comment]
Hard to fix, I need to create a filter in the catalog tab automatically when using Streamer mode... For now either create it yourself or just don't care about it, because if you try to play these tracks, they won't play and will be skipped.

**Comment by defvs** [comment]
Fixed with ab935896beaf0c87451b0c6772d05d1aef3160e7
Now trying to play some album will add the entire album to the playlist, excluding tracks if necessary
