### ISSUE TITLE
Playlist, index out of bounds / Empty playlist when stop music

### ISSUE THREAD

**Issue by Hallikas** [defvs/monsterutilities#9]
I did add few tracks on playlist (in Streamer mode). It was not possible to 'skip to next track' when not in randomize mode. So I had to put randomizer on.

Also I noticed following 'bug'? (I hope this is a bug).. I did add 3 songs on playlist, start playing first, pressing stop, and playlist is empty.

![image](https://user-images.githubusercontent.com/681531/65816272-4364c400-e202-11e9-9618-9b3404a064a7.png)

**Comment by defvs** [comment]
Pressing " Stop" clears the playlist, this is expected. You can click the "X" to close the player without clearing it.
The next button will not show up if 1. You have only one track in the playlist or are at the last one and 2. If random / repeat is enabled.

**Comment by defvs** [comment]
Please feel free to give your opinion on the Stop thing :)

**Comment by Hallikas** [comment]
Would it be possible to have option "Clear playlist on STOP"?

**Comment by Hallikas** [comment]
Btw, did you see that image that I attached on this issue? About that "Internal Error: java.lang.IndexOutOfBoundsException"

I'm quite sure, it's happening after all items on playlist is played, and it tries to find next song to play.

**Comment by defvs** [comment]
Yeah that's a bug. If you haven't got repeat enabled, it should stop the player without deleting the playlist. I'll try to see what's wrong, I'm a little busy this week.

**Comment by defvs** [comment]
Concerning more options, @Xerus2000 thinks it's best to not stack that many options, the Settings tab is a bit cluttered. I'll just make the stop button behave like the close button (ie. not clear the playlist)

**Comment by xeruf** [comment]
I agree, this seems a much more sensible default, and if the default is sensible you can reduce clutter in the settings ;)

**Comment by defvs** [comment]
Closing, feel free to reopen if bug still present.
